wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.18.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1650523060
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      3:
      - 2
      - 13
      4: 3.8.10
      5: 0.12.11
      6: 4.18.0.dev0
      8:
      - 5
batch_size:
  desc: null
  value: 4
data_path:
  desc: null
  value: /datasets/
eval_batch_size:
  desc: null
  value: 16
eval_interval:
  desc: null
  value: 500
generation_path:
  desc: null
  value: /project/Syllogistic-Commonsense-Reasoning/BART/generation_log/
kfold:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 5.0e-05
log_interval:
  desc: null
  value: 1000
max_len:
  desc: null
  value: 512
model_path:
  desc: null
  value: /project/Syllogistic-Commonsense-Reasoning/BART/model_log/
num_epochs:
  desc: null
  value: 1
num_iteration:
  desc: null
  value: 1000
project_name:
  desc: null
  value: BART Fine-Tuning Generation Only
save_interval:
  desc: null
  value: 5000
seed:
  desc: null
  value: 42
